/*
 * build_single_file.mjs
 *
 * Bundles reference-tool/ into ONE self-contained .html file that runs by
 * double-clicking, with no web server.
 *
 * Why this exists: ES modules cannot be loaded from a file:// origin. That makes
 * the multi-file version impossible to open directly on a PC and effectively
 * impossible on a phone. For a tool that has to work locally, a single file is
 * the only form that reliably does.
 *
 * The build is deliberately strict: if the module syntax changes in a way this
 * simple bundler cannot handle, it fails loudly rather than emitting a broken
 * bundle.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SPECS } from './reference-tool/js/specs.js';
import { checkRegistry } from './registry_guard.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, 'reference-tool');
const DIST = join(HERE, 'dist');

// Dependency order: a module must appear after everything it references.
const MODULES = ['js/config.js', 'js/specs.js', 'js/core.js', 'js/app.js'];

const problems = [];

/* ---------------------------------------------------- registry provenance guard
 *
 * A registry entry is a CLAIM about a real requirement. The guard refuses to ship
 * a claim that is incomplete or self-contradictory. Its rules live in
 * registry_guard.mjs, separately from this script, so that
 * _verify/test_registry_guard.mjs can feed it deliberately broken entries and
 * prove the rules actually fire.
 *
 * The guard is deliberately static. Measured behaviour needs a real JPEG encoder
 * and lives in _verify/check_specs.mjs. Both must pass before a release — the
 * original failure was a registry whose numbers were never checked against
 * anything at all, in either direction.
 */
const specCount = SPECS.length;
for (const p of checkRegistry(SPECS)) problems.push(p);

/** Strip module syntax so the files can share one scope. */
function stripModuleSyntax(code, name) {
  let out = code;

  // Single-line `import ... from '...';`
  out = out.replace(/^\s*import\s+[^;\n]*?from\s+['"][^'"]+['"]\s*;?\s*$/gm, '');

  // `export const|let|var|function|class|async function`
  out = out.replace(/^(\s*)export\s+(const|let|var|function|class|async\s+function)\b/gm, '$1$2');

  // Bare `export { a, b };`
  out = out.replace(/^\s*export\s*\{[^}]*\}\s*;?\s*$/gm, '');

  // Anything left means the bundler would silently produce a broken file.
  const leftoverImport = out.match(/^\s*import\s/m);
  const leftoverExport = out.match(/^\s*export\s/m);
  if (leftoverImport) problems.push(`${name}: unhandled import statement (is it multi-line?)`);
  if (leftoverExport) problems.push(`${name}: unhandled export statement`);

  return out;
}

/** Collisions between modules would silently overwrite one another in one scope. */
function checkCollisions(units) {
  const seen = new Map();
  for (const { name, code } of units) {
    const decls = code.matchAll(/^(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)/gm);
    for (const m of decls) {
      const id = m[1];
      if (seen.has(id)) problems.push(`name collision on "${id}": ${seen.get(id)} and ${name}`);
      else seen.set(id, name);
    }
  }
}

/* ------------------------------------------------------------------ bundle */
const units = MODULES.map((rel) => {
  const code = readFileSync(join(SRC, rel), 'utf8');
  return { name: rel, code: stripModuleSyntax(code, rel) };
});

checkCollisions(units);

const css = readFileSync(join(SRC, 'css', 'style.css'), 'utf8');

if (problems.length) {
  console.error('BUILD FAILED');
  for (const p of problems) console.error('  - ' + p);
  process.exit(1);
}

const banner = `/* Bundled single-file build. Source of truth: reference-tool/.
   Edit the modules there and re-run this script; do not edit this file. */`;

const js = [banner, '(function () {', "'use strict';", ...units.map((u) => u.code), '})();'].join('\n\n');

// Defensive: an inline script must not contain a closing script tag.
const safeJs = js.replace(/<\/script/gi, '<\\/script');
const safeCss = css.replace(/<\/style/gi, '<\\/style');

let html = readFileSync(join(SRC, 'index.html'), 'utf8');

const cssLink = /<link rel="stylesheet" href="css\/style\.css">/;
const jsTag = /<script type="module" src="js\/app\.js"><\/script>/;

if (!cssLink.test(html)) problems.push('index.html: stylesheet link not found (expected exactly one)');
if (!jsTag.test(html)) problems.push('index.html: module script tag not found (expected exactly one)');
if (problems.length) {
  console.error('BUILD FAILED');
  for (const p of problems) console.error('  - ' + p);
  process.exit(1);
}

html = html.replace(cssLink, `<style>\n${safeCss}\n</style>`);
html = html.replace(jsTag, `<script>\n${safeJs}\n</script>`);

// A data: URL manifest lets "Add to Home Screen" work on a hosted copy without
// a second file. Harmless on file://.
const manifest = {
  name: 'Photo & Signature Fitter',
  short_name: 'Photo Fitter',
  start_url: '.',
  display: 'standalone',
  background_color: '#0e1116',
  theme_color: '#1f6feb',
};
html = html.replace(
  '<title>',
  `<meta name="theme-color" content="#1f6feb">\n`
  + `<link rel="manifest" href="data:application/manifest+json,${encodeURIComponent(JSON.stringify(manifest))}">\n`
  + '<title>'
);

// Sanity: no local file references should survive.
const leftovers = [...html.matchAll(/(?:src|href)="(?!#|data:|https?:)([^"]+)"/g)].map((m) => m[1]);
if (leftovers.length) {
  console.error('BUILD FAILED — output still references local files:');
  for (const l of [...new Set(leftovers)]) console.error('  - ' + l);
  process.exit(1);
}

mkdirSync(DIST, { recursive: true });
const outFile = join(DIST, 'photo-signature-fitter.html');
writeFileSync(outFile, html, 'utf8');

const kb = (Buffer.byteLength(html) / 1024).toFixed(1);
const verified = SPECS.filter((s) => s.status === 'VERIFIED').length;
const marginal = SPECS.filter((s) => s.feasibility === 'marginal').length;
console.log('BUILD OK');
console.log('  output      : ' + outFile);
console.log('  size        : ' + kb + ' KB (one file, no dependencies)');
console.log('  modules     : ' + MODULES.join(', '));
console.log('  registry    : ' + specCount + ' requirements, ' + verified + ' VERIFIED, ' + marginal + ' flagged marginal');
console.log('  guard       : provenance + arithmetic checks passed');
console.log('  local refs  : none');
console.log('  opens from  : file:// (double-click) or any static host');
console.log('');
console.log('  Behavioural verification is separate and must also pass:');
console.log('    node _verify/check_specs.mjs      (every registry claim measured)');
console.log('    node _verify/run_all.mjs          (all suites)');
