/*
 * build_single_file.mjs
 *
 * Bundles reference-tool/ into ONE self-contained .html file that runs by
 * double-clicking, with no web server.
 *
 * Why this exists: ES modules cannot be loaded from a file:// origin. That makes
 * the multi-file version impossible to open directly on a PC and effectively
 * impossible on a phone. For a tool that has to work locally, a single file is
 * the only form that reliably does.
 *
 * THE BUNDLING ITSELF LIVES IN bundler.mjs, SHARED WITH THE CERTIFICATE TOOL.
 * This script used to carry its own copy of the module-syntax stripping, and that
 * copy is exactly how a real bug shipped. Its safety check was anchored the same
 * way as its strip regex, so a declaration sharing a line with the doc comment
 * above it (a doc comment immediately followed by `export function f()`) slipped
 * past BOTH: the build printed BUILD OK and emitted a file that died on open with
 * "Unexpected token 'export'". Only the single-file suite caught it, after the
 * build had already claimed success. One implementation, tested once, in
 * _verify/test_bundler.mjs.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bundle } from './bundler.mjs';
import { SPECS } from './reference-tool/js/specs.js';
import { checkRegistry } from './registry_guard.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, 'reference-tool');
const DIST = join(HERE, 'dist');

// Dependency order: a module must appear after everything it references.
const MODULES = ['js/config.js', 'js/specs.js', 'js/core.js', 'js/app.js'];

/* ---------------------------------------------------- registry provenance guard
 *
 * A registry entry is a CLAIM about a real requirement. The guard refuses to ship
 * a claim that is incomplete or self-contradictory. Its rules live in
 * registry_guard.mjs, separately from this script, so that
 * _verify/test_registry_guard.mjs can feed it deliberately broken entries and
 * prove the rules actually fire.
 *
 * The guard is deliberately static. Measured behaviour needs a real JPEG encoder
 * and lives in _verify/check_specs.mjs. Both must pass before a release — the
 * original failure was a registry whose numbers were never checked against
 * anything at all, in either direction.
 */
const specCount = SPECS.length;
const registryProblems = checkRegistry(SPECS);

if (registryProblems.length) {
  console.error('BUILD FAILED');
  for (const p of registryProblems) console.error('  - ' + p);
  process.exit(1);
}

// A data: URL manifest lets "Add to Home Screen" work on a hosted copy without
// a second file. Harmless on file://.
const manifest = {
  name: 'Photo & Signature Fitter',
  short_name: 'Photo Fitter',
  start_url: '.',
  display: 'standalone',
  background_color: '#0e1116',
  theme_color: '#1f6feb',
};

const result = bundle({
  srcDir: SRC,
  modules: MODULES,
  cssFile: join('css', 'style.css'),
  indexPath: join(SRC, 'index.html'),
  manifest,
  banner: `/* Bundled single-file build. Source of truth: reference-tool/.
   Edit the modules there and re-run this script; do not edit this file. */`,
});

if (!result.ok) {
  console.error('BUILD FAILED');
  for (const p of result.problems) console.error('  - ' + p);
  process.exit(1);
}

mkdirSync(DIST, { recursive: true });
const outFile = join(DIST, 'photo-signature-fitter.html');
writeFileSync(outFile, result.html, 'utf8');

const kb = (Buffer.byteLength(result.html) / 1024).toFixed(1);
const verified = SPECS.filter((s) => s.status === 'VERIFIED').length;
const derived = SPECS.filter((s) => s.status === 'DERIVED').length;
const unverified = SPECS.filter((s) => s.status === 'UNVERIFIED').length;
const marginal = SPECS.filter((s) => s.feasibility === 'marginal').length;
console.log('BUILD OK');
console.log('  output      : ' + outFile);
console.log('  size        : ' + kb + ' KB (one file, no dependencies)');
console.log('  modules     : ' + MODULES.join(', '));
// DERIVED and UNVERIFIED are reported separately rather than folded into one
// "not verified" count: they are different claims, and a summary that blurs them
// is the same mistake the status field was split up to avoid.
console.log('  registry    : ' + specCount + ' requirements, ' + verified + ' VERIFIED, ' +
  derived + ' DERIVED, ' + unverified + ' UNVERIFIED, ' + marginal + ' flagged marginal');
console.log('  guard       : provenance + arithmetic checks passed');
console.log('  local refs  : none');
console.log('  opens from  : file:// (double-click) or any static host');
console.log('');
console.log('  Behavioural verification is separate and must also pass:');
console.log('    node _verify/check_specs.mjs      (every registry claim measured)');
console.log('    node _verify/run_all.mjs          (all suites)');
